language: node_js
node_js:
- 4
script:
- bash .build.sh
after_success:
- bash .deploy.sh
env:
  global:
    secure: QYahdiNJbPTcQ5Pug79EZNyMg7iHQ1WVqQ4UDsESJqwEf5AiHAPnT5dyeSyQpoHMyc6XN3Kp2VG6dZ5aj/Pw/19Fma847ARu05fCkY6BOZChzZcC1cCSvo+pdbe7NBSQsxQullUcuy/EorlnUoEs6JuNyBL/qVS/VIgOzw4GiHx1+LR4zp+KwNg9/flX/2H+TVAlthWUHyF5/y7aE4UyPz7OmgmfjOvOM0MkeW5zmlxd8qOHCoS0WndT8NTrEYAggELsBWMCRQrudrOfHfmu2Ycnx5Av/jwu0ihaHzGBDolYfO6z+v8jlHehe90FsEH/uzAR8xZQyzQXg/8oXAJxLLmML0JR+db0tblXTDhlFqkS5uhac96q+ug5kmm78snK0qpslf/lnfWwe4hMJr9lJYIywY3eYAMIArh/39RiUFn1W0ZkYhVt+BD/ZiNj0htHrm4o+pC8wUe1xDM3YI453vd8riBF/XYDgTyUv/g9YpWNqjMtCsgEEZngRcufT4FDbRhIqQFqQRcf6u93bzLV0TD+7/cqocOyzL+uGmE2/TuK3lj85E0NdqvmVE4t+hRqYZj72e4vcEC5dJqz3p+oumDrA1zJPQTfDrkNNC/m35+4nw4OrfpzDOlUcSx2egwTXUSaR41HFL3Kk0YnHmHrH6wHIrQeDRY4Ea8yl+YTpGI=
notifications:
  slack:
    secure: llNnXYQ/1R8QTDvodbM5MfLJMIrOSvYMvJY7Btit0vbwXfEgCpcoPNgQZK0Ol1yergnWkwwWNhMvBi5TQEaCJq5R7jHjD0XDun7lgrVMsF3TdpZXq1Op7iHpO2MfojDbu6owNIbe1jsX0LZTud48KJkNXInnbVPzfOwlTUgweXuUAs3RFWb7+Z8KcPa5pBbVIUj363DWmCYzB0MfvcYq7u7ualCY/qgiKG1/KIeHUjOoRfJnpzZztHHkQPkpqvD00DnHgLkcAXg5SPRon9fiv6drDXFOtQ7juI2pSHiBpsmvFKAjq6w83MMnNUyAzRNRWPwTk9TKWJiM2iQ+I4DWm4FOq4GHOxoXami094aiuv4AznMumZRIuN33+Ac/OsFdo2v1t/Efjx1sZyTGp/uYvMKtRtLkiO06r1bhowSkpseAv2ivbAcJGqupYvCApJZPYsF8EM2Jx1MY2Nw2QpBK1Y1BYvbS0UiTAVa7e6ECHrys1+wj07l8zvazJoa2SF/vss7KbCJR6G8qVtIgW2HaeWZeS8leFfzXC/v658zrp9TQnj4BK5JFQISyLLBzmxWPsWpwtCoMJH6z4WxIioy9yiBD//6ZMqsSi9cFbtMtEFR8BesQlOm380I1pjn4SaNr4H6LyX3Lzog0lylXDkP5Q51KjivslS/fZbwsL7/p3dk=
