language: node_js
node_js:
  - 4
script:
- bash .build.sh
after_success:
- bash .deploy.sh
env:
  global:
    secure: "iSlKFV+Xp86s5ElTn3Dc/DUBD1TrLkUy8XSsw6ZnNCPDlw2vxE1xE5QBwUU8CV1KYr4+8W1DC1L0kbMibqU7TGB2Gp/SQzmgSwHB0xI3eAWiOzoEUe0qIWl1T22WO+1+Prd6lKgHbzsHClafHl8h8CPeBRzCsGYK2QIvfAQtZXiSS+fFkCAad9xz3U/MOfCL0FeaV8PjFbJrCs76ZCbnt5jcd4q1FYdiUQyoSP9rcTzH/IfzLPU/FWxjx8PadE0f19NKuWTKryibde431nnZJNwos6DGNy66awwQJ1vpZ4PC7u7OAKwlZasW8TCoBaaofg6+R4I3EvwgtpnpEdfjgMII89Qz6J+N+6iac0uB+a1ZAOyhPP6IKl/JYe0x2VAV9mdSDkcEHZTCZC03zqpX1dyCWA8DOhFPW5YhCu+iZBOFkGXnYVYrV//VLVapINtr4ZQ3aF/Nej7b0WX4QLMjqJYlHWlkB/VulfQgoMynuO+mbOlsCVRDN1fSgJ3CygoMs0bM+ZZuqOviGxG6Tug6im8/78zkIICxolprsoKdZurI7ceRlvZenZDWGLRB6gPxzaSi3o1wkqgaE5kZ79Rtr6CR6PdfpeHGJovxRxcYM9bDt+jwe1G2N27+t74H9cxQbGMpDWj3L2PKoYD8PbqAbCgGD1vMHvmMCAscdQ1/SD8="
notifications:
  slack:
    secure: llNnXYQ/1R8QTDvodbM5MfLJMIrOSvYMvJY7Btit0vbwXfEgCpcoPNgQZK0Ol1yergnWkwwWNhMvBi5TQEaCJq5R7jHjD0XDun7lgrVMsF3TdpZXq1Op7iHpO2MfojDbu6owNIbe1jsX0LZTud48KJkNXInnbVPzfOwlTUgweXuUAs3RFWb7+Z8KcPa5pBbVIUj363DWmCYzB0MfvcYq7u7ualCY/qgiKG1/KIeHUjOoRfJnpzZztHHkQPkpqvD00DnHgLkcAXg5SPRon9fiv6drDXFOtQ7juI2pSHiBpsmvFKAjq6w83MMnNUyAzRNRWPwTk9TKWJiM2iQ+I4DWm4FOq4GHOxoXami094aiuv4AznMumZRIuN33+Ac/OsFdo2v1t/Efjx1sZyTGp/uYvMKtRtLkiO06r1bhowSkpseAv2ivbAcJGqupYvCApJZPYsF8EM2Jx1MY2Nw2QpBK1Y1BYvbS0UiTAVa7e6ECHrys1+wj07l8zvazJoa2SF/vss7KbCJR6G8qVtIgW2HaeWZeS8leFfzXC/v658zrp9TQnj4BK5JFQISyLLBzmxWPsWpwtCoMJH6z4WxIioy9yiBD//6ZMqsSi9cFbtMtEFR8BesQlOm380I1pjn4SaNr4H6LyX3Lzog0lylXDkP5Q51KjivslS/fZbwsL7/p3dk=
